/** Stable machine-readable error codes returned in `error.code`. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REUSED: 'TOKEN_REUSED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',

  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  EVENT_FULL: 'EVENT_FULL',
  EVENT_NOT_PUBLISHED: 'EVENT_NOT_PUBLISHED',
  EVENT_IN_PAST: 'EVENT_IN_PAST',
  EVENT_NOT_SINGLE_DAY: 'EVENT_NOT_SINGLE_DAY',
  ALREADY_ATTENDING: 'ALREADY_ATTENDING',
  NOT_ATTENDING: 'NOT_ATTENDING',
  INVITE_REQUIRED: 'INVITE_REQUIRED',
  GENDER_BALANCE_FULL: 'GENDER_BALANCE_FULL',

  BLOCKED: 'BLOCKED',
  SELF_ACTION: 'SELF_ACTION',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  LOVE_REQUESTS_DISABLED: 'LOVE_REQUESTS_DISABLED',
  REQUEST_EXPIRED: 'REQUEST_EXPIRED',
  NOT_CONNECTED: 'NOT_CONNECTED',
  MESSAGING_NOT_ALLOWED: 'MESSAGING_NOT_ALLOWED',

  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_VERIFIED: 'PAYMENT_NOT_VERIFIED',
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
  ABUSE_DETECTED: 'ABUSE_DETECTED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
